baseURL = "https://new.sensorgnome.org"
languageCode = "en-us"
title = "New Sensorgnome Site"
defaultContentLanguage = "en"
theme = "vanilla-bootstrap-hugo-theme"

# Uncomment below to enable syntax highlighting
# pygmentsCodefences = true
# pygmentsCodefencesGuessSyntax = true
# See https://xyproto.github.io/splash/docs/all.html for more styles
# pygmentsStyle = "pygments"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.nav]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Status"
    pre = "activity"
    url = "/status/"
    weight = 2
  [[menu.nav]]
    name = "About"
    pre = "info"
    url = "/about/"
    weight = 4
  [[menu.nav]]
    name = "Source"
    pre = "github"
    url = "/source/"
    weight = 4

[params]
  includeBootstrapJs = true

  showActiveNav = true
  containerMaxWidth = "700px"
  dateFormat = "Jan 2, 2006"
  homeText = "Sensorgnome"
  footerText = "[SensorgnomeServer](https://github.com/jbrzusto/sensorgnomeServer) uses [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)"
  hideFooter = false
